Names={
'S033'...
'S037'...% 'S028'...'S034'...
'S040'...
'S041'...
'S042'...
'S043'...
'S044'...
'S047'...
'S048'...% 'S049'...'S056'...% 'S059'...'S058'...
'S060'...% 'S062'...
'S064'...
'S065'...
'S068'...
'S069'...
'S070'...
'S072'...
'S073'...
'S074'...
'S075'...
'S077'...
'S078'...
'S080'...
'S081'...
'S082'...
'S084'...
'S085'...
'S089'...%'S090'...
'S091'...
'S098'...
'S099'...
'S100'...
'S101'...
'S102'...
'S103'...
'S105'...
'S106'...
'S107'...
'S108'...
};
path='G:\Cortical_spinalcord\MRIdata';
for k=1:length(Names)
    p=spm_select('FPList',[path,'\',Names{k}],'DTIeddy_S0.nii');
    v=spm_vol(p);
    w=spm_read_vols(v);
    R=zeros(size(w));
    p2=spm_select('FPList',[path,'\',Names{k},'\splitImage\'],[Names{k},'_Brain_B0.nii']);
    v2=spm_vol(p2);
    w2=spm_read_vols(v2);
    R2=zeros(size(w2));
    [m,n,~]=size(w);
%    load(['G:\Cortical_spinalcord\FiberTracts\tha_x_Tracts\',Names{k},'\tha_S2\tha_S2_R_seg.mat']);
    load(['G:\Cortical_spinalcord\FiberTracts\tha_spinalcordFiberTracts\',Names{k},'\',Names{k},'_tha_spinal_seg.mat']);
    for i=1:length(TractFE)
        for j=1:length(TractFE{1,i})
            if(TractFE{1,i}(j,1)==0&&TractFE{1,i}(j,2)==0&&TractFE{1,i}(j,3)==1||TractFE{1,i}(j,1)==0&&TractFE{1,i}(j,2)==1&&TractFE{1,i}(j,3)==0)
                tmp{1,i}(j,:)=Tracts{1,i}(j,:);
            end
        end
    end
    tmp=Tracts;
    tmp(cellfun(@isempty,tmp))=[];
    for a=1:length(tmp)
        for b=length(tmp{1,a}):-1:1
            if(tmp{1,a}(b,:)==[0,0,0])
                tmp{1,a}(b,:)=[];
            end
        end
    end
    voxel_cord={};
    for i=1:length(tmp)
        tmp{1,i}(:,1)=tmp{1,i}(:,1)./1.2;
        tmp{1,i}(:,2)=tmp{1,i}(:,2)./1.2;
        tmp{1,i}(:,3)=tmp{1,i}(:,3)./4;
        voxel_cord{1,i}=[n-tmp{1,i}(:,2)+1,m-tmp{1,i}(:,1)+1,tmp{1,i}(:,3)-(70-size(w2,3))];
        voxel_cord{1,i}=round(voxel_cord{1,i});
        ind = sub2ind(size(w),voxel_cord{1,i}(:,1),voxel_cord{1,i}(:,2),voxel_cord{1,i}(:,3));
        R2(ind)=1;
    end
    tmp_v=v;
    tmp_v.dim=size(w2);
  %  tmp_v.fname=['G:\Cortical_spinalcord\corrpoints2ICBM\frequencyImage\corticalspinal_register\brain\',Names{k},'_S2_R.nii'];//存储路径，按照自己需求改
    spm_write_vol(tmp_v,R2);
    clear R tmp;
end
