Names={
'S028'...
'S033'...
'S034'...
'S037'...
'S040'...
'S041'...
'S042'...
'S043'...
'S044'...
'S047'...
'S048'...
'S049'...
'S056'...
'S058'...
'S059'...
'S060'...
'S062'...
'S064'...
'S065'...
'S068'...
'S069'...
'S070'...
'S072'...
'S073'...
'S074'...
'S075'...
'S077'...
'S078'...
'S080'...
'S081'...
'S082'...
'S084'...
'S085'...
'S089'...
'S090'...
'S091'...
'S098'...
'S099'...
'S100'...
'S101'...
'S102'...
'S103'...
'S105'...
'S106'...
'S107'...
'S108'...
};
arc_length_L=1:21;
% arc_length_R=1:50;
for k=1:length(Names)
    p1=spm_select('FPList','F:\data\MRIdata\subject_brain_spinal\brain\',[Names{k},'_FA.nii']);
    v1=spm_vol(p1);
    w1=spm_read_vols(v1);
    p2=spm_select('FPList','F:\data\MRIdata\subject_brain_spinal\brain\',[Names{k},'_MD.nii']);
    v2=spm_vol(p2);
    w2=spm_read_vols(v2);
    p3=spm_select('FPList','F:\data\MRIdata\subject_brain_spinal\brain\',[Names{k},'_AD.nii']);
    v3=spm_vol(p3);
    w3=spm_read_vols(v3);
    p4=spm_select('FPList','F:\data\MRIdata\subject_brain_spinal\brain\',[Names{k},'_RD.nii']);
    v4=spm_vol(p4);
    w4=spm_read_vols(v4);
    [M,N,P]=size(w1);
    X=1:N;
    Y=1:M;
    Z=1:P;
    load(['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\',Names{k},'_pv-tha_R.mat']);
    load('G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\CordMask\pv_tha_R\tha_PV_R.mat');
    for i=1:length(Tracts)
        for j=1:length(Tracts{1,i})
            if(CoordMask(i,j)==1)
                FA(i,j)=nan;
                MD(i,j)=nan;
                AD(i,j)=nan;
                RD(i,j)=nan;
            else
                Cord_tmp=Tracts{1,i};
                FA(i,j)=interp3(X,Y,Z,w1,Cord_tmp(j,2),Cord_tmp(j,1),Cord_tmp(j,3));
                MD(i,j)=interp3(X,Y,Z,w2,Cord_tmp(j,2),Cord_tmp(j,1),Cord_tmp(j,3));
                AD(i,j)=interp3(X,Y,Z,w3,Cord_tmp(j,2),Cord_tmp(j,1),Cord_tmp(j,3));
                RD(i,j)=interp3(X,Y,Z,w4,Cord_tmp(j,2),Cord_tmp(j,1),Cord_tmp(j,3));
            end
        end
    end
    for m=1:size(FA,1)
       fig_FA= plot(arc_length_L,FA(m,:),'b');
       hold on;
    end
    title([Names{k},'_FAarclength']);
    saveas(fig_FA,['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\FA_arclength.fig']);
    hold off;
    save(['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\',Names{k},'_FA.mat'],'FA');
    for m=1:size(MD,1)
       fig_MD= plot(arc_length_L,MD(m,:),'b');
       hold on;
    end
    title([Names{k},'_MDarclength']);
    saveas(fig_MD,['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\MD_arclength.fig']);
    hold off;
    save(['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\',Names{k},'_MD.mat'],'MD');
    
   for m=1:size(AD,1)
       fig_AD= plot(arc_length_L,AD(m,:),'b');
       hold on;
    end
    title([Names{k},'_ADarclength']);
    saveas(fig_AD,['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\AD_arclength.fig']);
    hold off;
    save(['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\',Names{k},'_AD.mat'],'AD');
    
   for m=1:size(RD,1)
       fig_RD= plot(arc_length_L,RD(m,:),'b');
       hold on;
    end
    title([Names{k},'_RDarclength']);
    saveas(fig_RD,['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\RD_arclength.fig']);
    hold off;
    save(['G:\Cortical_spinalcord\FiberTracts\std2native_tha-x\',Names{k},'\pv-tha\pv-tha_R\',Names{k},'_RD.mat'],'RD');
end
