 Names={
'S028'...
'S033'...
'S034'...
'S037'...
'S040'...
'S041'...
'S042'...
'S043'...
'S044'...
'S047'...
'S048'...
'S049'...
'S056'...
'S058'...
'S059'...
'S060'...
'S062'...
'S064'...
'S065'...
'S068'...
'S069'...
'S070'...
'S072'...
'S073'...
'S074'...
'S075'...
'S077'...
'S078'...
'S080'...
'S081'...
'S082'...
'S084'...
'S085'...
'S089'...
'S090'...
'S091'...
'S098'...
'S099'...
'S100'...
'S101'...
'S102'...
'S103'...
'S105'...
'S106'...
'S107'...
'S108'...
};
%  S034找不到acc,所以在做acc的时候暂时屏蔽
filepath='G:\Cortical_spinalcord\FiberTracts\tha_spinalcordFiberTracts';
for k=1:length(Names)
    load([filepath,'\',Names{k},'\',Names{k},'_tha_spinal_seg_resample50.mat']);
%     load(['G:\Cortical_spinalcord\纤维束相关结果图\结果图汇总\多个体纤维束底板\paintolerance\S2-tha\',Names{k},'_S2-tha_PT_R.mat']);
    load([filepath,'\',Names{k},'\',Names{k},'_tha_spinal_seg_flipped.mat']);
   for a=1:length(fg_out.fibers)
       if(fg_out.fibers{a,1}(3,1)<fg_out.fibers{a,1}(3,end))
        fg_out.fibers{a,1}=fliplr(fg_out.fibers{a,1});   
       end
       if(Tracts{1,a}(1,3)<Tracts{1,a}(end,3))
            Tracts{1,a}=flipud(Tracts{1,a});   
       end
       for i=1:length(Tracts)
           TractFE{1,i}=ones(size(TractFE{1,i},1),3).*[0.3,0.1,0.86];
           pairpoint1=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,19)'];
           pairpoint2=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,20)'];
           d1=pdist(pairpoint1);
           d2=pdist(pairpoint2);
           pairpoint3=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,37)'];
           pairpoint4=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,38)'];
           d3=pdist(pairpoint3);
           d4=pdist(pairpoint4);
           pairpoint5=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,49)'];
           pairpoint6=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,50)'];
           d5=pdist(pairpoint5);
           d6=pdist(pairpoint6);
%            pairpoint7=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,18)'];
%            pairpoint8=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,19)'];
%            d7=pdist(pairpoint7);
%            d8=pdist(pairpoint8);
%            pairpoint9=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,22)'];
%            pairpoint10=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,23)'];
%            d9=pdist(pairpoint9);
%            d10=pdist(pairpoint10);
%            pairpoint11=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,31)'];
%            pairpoint12=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,34)'];
%            d11=pdist(pairpoint11);
%            d12=pdist(pairpoint12);
%            pairpoint13=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,36)'];
%            pairpoint14=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,39)'];
%            d13=pdist(pairpoint13);
%            d14=pdist(pairpoint14);
%            pairpoint15=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,43)'];
%            pairpoint16=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,46)'];
%            d15=pdist(pairpoint15);
%            d16=pdist(pairpoint16);
%            pairpoint17=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,49)'];
%            pairpoint18=[fg_out.fibers{i,1}(:,1)';fg_out.fibers{i,1}(:,50)'];
%            d17=pdist(pairpoint17);
%            d18=pdist(pairpoint18);

           for j=1:length(Tracts{1,i})
               if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d1&& pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d2)
                    TractFE{1,i}(j,:)=[0,1,0];
               end
               if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d3 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d4)
                    TractFE{1,i}(j,:)=[0,1,0];
               end
               if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d5 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d6)
                    TractFE{1,i}(j,:)=[0,1,0];
               end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>d7 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d8)
%                     TractFE{1,i}(j,:)=[0,1,0];
%                end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>d9 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d10)
%                     TractFE{1,i}(j,:)=[0,1,0];
%                end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d11 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d12)
%                     TractFE{1,i}(j,:)=[0,1,0];
%                end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d13 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d14)
%                     TractFE{1,i}(j,:)=[0,1,0];
% 
%                end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d15 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d16)
%                     TractFE{1,i}(j,:)=[0,1,0];
%                end
%                if(pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])>=d17 && pdist([fg_out.fibers{i,1}(:,1)' ; Tracts{1,i}(j,:)])<=d18)
%                     TractFE{1,i}(j,:)=[0,1,0];
%                end
           end
            
       end
   end
   save(['G:\Cortical_spinalcord\纤维束相关结果图\结果图汇总\多个体纤维束底板\PLSR\新结果\spinal\RCPS\',Names{k},'_tha-spinal_RCPS .mat'],...
       'FList','TractAng','TractFA','TractFE','TractGEO','TractL','TractLambdas',...
       'TractMask','TractMD','Tracts','VDims');
   clear FList TractAng TractFA TractFE TractGEO TractL TractLambdas TractMask TractMD Tracts VDims;
end