%% 程序功能：将个体的FA,MD,AD,RD变成一个综合指标
%
% Author: LiangMa,XD University
%%
%矩阵数据标准化
Names={
'S028'...
'S033'...
'S034'...
'S037'...
'S040'...
'S041'...
'S042'...
'S043'...
'S044'...
'S047'...
'S048'...
'S049'...
'S056'...
'S058'...%'S059...'
'S060'...%'S064...'
'S062'...
'S065'...
'S068'...
'S069'...
'S070'...
'S072'...
'S073'...
'S074'...
'S075'...
'S077'...
'S078'...
'S080'...
'S081'...
'S082'...
'S084'...
'S085'...
'S089'...
'S090'...
'S091'...
'S098'...
'S099'...
'S100'...
'S101'...
'S102'...
'S103'...
'S105'...
'S106'...
'S107'...
'S108'...
};
filepath='G:\Cortical_spinalcord\FiberTracts\tha_x_Tracts';
all_data_spinal=[];
for i=1:length(Names)
    FA_L(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_FA_meancorfibers_50_L.mat']);
    AD_L(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_AD_meancorfibers_50_L.mat']);
    MD_L(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_MD_meancorfibers_50_L.mat']);
    RD_L(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_RD_meancorfibers_50_L.mat']);
    FA_R(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_FA_meancorfibers_50_R.mat']);
    AD_R(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_AD_meancorfibers_50_R.mat']);
    MD_R(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_MD_meancorfibers_50_R.mat']);
    RD_R(i)=load([filepath,'\',Names{i},'\tha_S2\meanfiber\',Names{i},'_RD_meancorfibers_50_R.mat']);
end
for j=1:50
    for i=1:44
        tmp(i,1)=spinalFA(i).meancorfiber(1,j);
        tmp(i,2)=spinalAD(i).meancorfiber(1,j);
        tmp(i,3)=spinalMD(i).meancorfiber(1,j);
        tmp(i,4)=spinalRD(i).meancorfiber(1,j);
    end
    all_data_spinal=[all_data_spinal;tmp];
end
%PCA分解
[coeff,score,latent,tsquared,explained,mu] = pca(zscore(all_data_spinal,0,1));
figure(1);
pareto(explained);
xlabel('Principal Component');
ylabel('Variance Explained (%)');
figure(2);
biplot(coeff(:,1:2),'score',score(:,1:2));
for i=1:44
    pc1_data(i,:)=score(i:44:end,1);
    pc2_data(i,:)=score(i:44:end,2);
    pc3_data(i,:)=score(i:44:end,3);
end

for i=1:44
    spinal_pc1_data(i,:)=pca_spinal(i:44:end,1);
    spinal_pc2_data(i,:)=pca_spinal(i:44:end,2);
%     pc3_data(i,:)=score(i:44:end,3);
end
% save('G:\Cortical_spinalcord\挑选过的做相关所需的数据\pc1_data.mat','pc1_data');
% save('G:\Cortical_spinalcord\挑选过的做相关所需的数据\pc2_data.mat','pc2_data');
% save('G:\Cortical_spinalcord\挑选过的做相关所需的数据\pc1_pc2_data.mat','pc1_pc2_data');







