Names={
'S028'...
'S033'...
'S034'...
'S037'...
'S040'...
'S041'...
'S042'...
'S043'...
'S044'...
'S047'...
'S048'...
'S049'...
'S056'...
'S058'...
'S059'...
'S060'...
'S062'...
'S064'...
'S065'...
'S068'...
'S069'...
'S070'...
'S072'...
'S073'...
'S074'...
'S075'...
'S077'...
'S078'...
'S080'...
'S081'...
'S082'...
'S084'...
'S085'...
'S089'...
'S090'...
'S091'...
'S098'...
'S099'...
'S100'...
'S101'...
'S102'...
'S103'...
'S105'...
'S106'...
'S107'...
'S108'...
};

for k=1:length(Names)
    load(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\fibersPreproc\',Names{k},'interped_FA_70_L.mat']);
    mkdir(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\','cluster']);
    for i=1:size(FA_tmp,1)
        for j=1:size(FA_tmp,1)
            CorMatrix(i,j)=corr(FA_tmp(i,:)',FA_tmp(j,:)');
        end
    end
    sum_cor=sum(CorMatrix,2);
    tmp=max(sum_cor);
    sum_cor=sum_cor./tmp;
    cluster_cor=kmeans(sum_cor,2);
    ind1=find(cluster_cor==1);
    ind2=find(cluster_cor==2);
    arc_length=1:70;
    figure(1)
    for a=1:size(ind1,1)
       fig1=plot(arc_length,FA_tmp(ind1(a),:),'b');
       hold on;
%        TractFA{1,ind1(i)}(1:end)=0.001;
    end
     savefig(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\cluster\',Names{k},'_FA_cluster1_L.fig']);
     hold off;
    figure(2);
    for b=1:size(ind2,1)
%         TractFA{1,ind2(j)}(1:end)=0.008;
        fig2=plot(arc_length,FA_tmp(ind2(b),:),'r');
        hold on;
    end
     savefig(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\cluster\',Names{k},'_FA_cluster2_L.fig']);
     hold off;

    FA_cluster1=FA_tmp(ind1,:);
    FA_cluster2=FA_tmp(ind2,:);

    mean_cluster1=mean(FA_cluster1);
    mean_cluster2=mean(FA_cluster2);
    save(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\cluster\',Names{k},'_FA_cluster1_70_L.mat'],'FA_cluster1');
    save(['G:\Cortical_spinalcord\FiberTracts\Cortex_SpinalcordFiberTracts\',Names{k},'\cluster\',Names{k},'_FA_cluster2_70_L.mat'],'FA_cluster2');
%     figure(1);
%     plot(arc_length,mean_FA_cluster1);
%     figure(2);
%     plot(arc_length,mean_FA_cluster2);
%     hold off;
    clear FA_tmp FA_cluster1 FA_cluster2 ind1 ind2 sum_cor cluster_cor CorMatrix;
end
